version: '3.7'

services:
  rabbit:
      image: "rabbitmq:3-management"
      environment:
        RABBITMQ_DEFAULT_USER: "guest"
        RABBITMQ_DEFAULT_PASS: "guest"
      ports:
        - "5672:5672"
        - "15672:15672"
  clickhouse-server:
       image: yandex/clickhouse-server
       ports:
        - '8123:8123'
       networks:
        - clickhouse_network
networks:
  clickhouse_network:
    driver: bridge